### ISSUE TITLE
Wombat incorrectly rewriting URL

### ISSUE THREAD

**Issue by calbon2702** [webrecorder/wombat#119]
I am attempting to capture this website using Pywb but the AJAX request is not being rewritten properly so the request that loads the body of the content returns a 404.

Webarchive: https://webarchive.nrscotland.gov.uk/https://digitalpublications.parliament.scot/
Live Site: https://digitalpublications.parliament.scot/

![image](https://user-images.githubusercontent.com/60651886/234299519-e3e5718d-6734-418e-9147-a85883254814.png)

**Comment by ikreymer** [comment]
Just tested a new capture of `https://digitalpublications.parliament.scot/` with archiveweb.page and it replayed both with replayweb.page and pywb:
<img width="1440" alt="Screen Shot 2023-07-28 at 8 59 39 AM" src="https://github.com/webrecorder/wombat/assets/1015759/aca7cace-61ea-44c8-98b3-fb37fb518fd8">

That URL was correctly rewritten as `
http://localhost:8080/test/20230728155455mp_/https://digitalpublications.parliament.scot/Home/RecentReportsPartial?_=1690559695232`

We can't easily test other providers' services, and don't have access to that particular capture. I'd recommend updating to latest pywb and seeing if the issue is resolved.
