### ISSUE TITLE
Infinite loop (resource loaded ad infinitum)

### ISSUE THREAD

**Issue by wsdookadr** [webrecorder/wombat#92]
Consider the following WARC file. It was generated using `wget --warc-file` for the [following web page](https://asone.ai/polymath/index.php?title=DHJ(2.7)). This file wasn't altered in any way, left untouched just as wget has generated it.

Uploading it to [https://replayweb.page](https://replayweb.page) and opening the web page will cause it to load the following resource. This generates more and more traffic, and the web page will not finish loading because it's waiting on the resources to finish loading.

`https://replayweb.page/w/id-ef97d2d3b783/20220708150914js_/https://asone.ai/polymath/load.php?debug=false&lang=en&modules=jquery,mediawiki&only=scripts&skin=monobook&version=20200401T175219Z`

This is indeed an edge-case. For the most part wombat works well in what it does, so this is an isolated situation.

[r1.warc.gz](https://github.com/webrecorder/wombat/files/9073115/r1.warc.gz)

Versions used:
- GNU Wget 1.21 (from Debian 11 packages)

**Comment by ikreymer** [comment]
Taking a quick look, yes, it appears there's an infinite loop due to certain files being missing and the fuzzy matching choosing the wrong file, creating an infinite loading loop of adding a new script. It looks like the WARC contains 2 files with  `load.php?...`, but the site has 4 such URLs. The page is dynamic and can not be properly archived with just wget, as it loads additional scripts dynamically via JS.
Testing with both archiveweb.page extension or browsertrix crawler, the issue does not appear.
For this reason, would not recommend using wget to archive anything but pages that are completely static and containing no dynamic JS.
