### ISSUE TITLE
Difference in the requested uris between Chromium and Firefox for the same resource

### ISSUE THREAD

**Issue by wsdookadr** [webrecorder/wombat#93]
So I'm using both Firefox and Chromium to view a ZIM file served by kiwix-serve.
Consider the following [web page](http://localhost:8083/big_2022-07/A/abstract.ups.edu/aata/section-method-of-repeated-squares.html).

If I view it in Firefox, the web page itself will load, but many resources will fail (primarily CORS requests to domains different than the one of the web page), leading to a partially rendered web page.

An example of such a resource:
* Actual uri in WARC: `https://www.google.com/cse/static/style/look/v4/default.css`
* In Chromium: `http://localhost:8083/big_2022-07/A/www.google.com%2Fcse%2Fstatic%2Fstyle%2Flook%2Fv4%2Fdefault.css`
* In Firefox: `http://localhost:8083/big_2022-07/A/cs_/https://www.google.com/cse/static/style/look/v4/default.css`

So the needed data is in the WARC and in the ZIM file for sure, but Firefox uses the wrong uri, while Chromium successfully loads the resource with the right uri.

Some places where the URI gets encoded are near calls to encodeURIComponent: [1](https://github.com/webrecorder/wombat/blob/2a70753f6504809f170a0495979015bb64f0877d/src/autoFetcher.js#L149) , [2](https://github.com/webrecorder/wombat/blob/2a70753f6504809f170a0495979015bb64f0877d/src/autoFetcherProxyMode.js#L146) , [3](https://github.com/webrecorder/wombat/blob/7d970dfe17da3b7136374440b494422ea26844e9/src/wombat.js#L2216) , [4](https://github.com/webrecorder/wombat/blob/7d970dfe17da3b7136374440b494422ea26844e9/src/wombat.js#L2471).

Versions used:
- Chromium 97.0.4692.99 built on Debian 11.2
- Mozilla Firefox 91.5.0esr (from debian packages)
- kiwix-tools 3.3.0
- browsertrix-crawler version 0.7.0-beta.1 (as repoted by `docker run webrecorder/browsertrix-crawler crawl --version
0.7.0-beta.1` , [this docker image](https://hub.docker.com/layers/browsertrix-crawler/webrecorder/browsertrix-crawler/0.7.0-beta.1/images/sha256-e844d9608ae2c108f214c07cc010dc945c947ba5aea1e73ab4340d02add575dc?context=explore) )

**Comment by ikreymer** [comment]
I wasn't able to repro an issue with wombat.js here, `encodeURIComponent("https://www.google.com/cse/static/style/look/v4/default.css")` evaluates to the same on both Chrome and Firefox.

Testing the site with WARC and WACZ replay on both Firefox and Chrome, I wasn't able to repro the issue.

The particular difference you're seeing is due to how ZIM replay works, there are actually two requests made, Chromium shows both, while Firefox does not show the traffic from the service worker (unfortunately), making it more confusing.
eg. Chromium is showing both `http://localhost:8083/big_2022-07/A/cs_/https://www.google.com/cse/static/style/look/v4/default.css` (from browser to service worker) and `http://localhost:8083/big_2022-07/A/www.google.com%2Fcse%2Fstatic%2Fstyle%2Flook%2Fv4%2Fdefault.css` (from service worker to upstream), while Firefox only shows the first.

Closing as this is not related to wombat.js, should probably be discussed in the warc2zim issue.
